#!/usr/bin/env bash

###########################################################################################
#
#   Make autograder:
#       - Cleans up files (all .DS_Store, staging/target, staging/src/main*)
#       - Creates a top level zip of only the essential files required for the
#           autograder to actually run
#
###########################################################################################

# Root folder of autograder
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && cd ../ && pwd )"

cd $DIR


echo "Removing node_modules directories"
find . -name node_modules -ls -and -exec /bin/rm -rf {} \;


find . -name ".DS_Store" -exec rm -rf {} \;
rm -f "$DIR"/Autograder.zip
rm -rf "$DIR"/staging_main/src/main/*
rm -rf "$DIR"/staging_main/coverage/*
rm -rf "$DIR"/staging_main/jest-output.json*
rm -rf "$DIR"/staging_test/src/*
zip -r Autograder.zip . -x "localautograder/*" "*.git*"
